[signal-parameter]
t-start=0.0  
t-end=400.0  
dt=0.2       
 
[mimick-sxs]
times_from-sxs=false
error-from-sxs=false 
sxs-simulation=SXS:BBH:0305

[event-parameter]
final-mass=1.0
final-spin=0.67
final-charge=0.0

[kerr-model]
#Kerr qnms
kerr-amplitudes={"2220": 1.0, "2221": 1.0}
kerr-phases={"2220": 3.1415, "2221": 1.5}